# This file is cloned from https://github.com/espressif/esp-idf/tree/master/tools/docker

FROM ghcr.io/volinhtruc/bico_esp-idf_container:idf_release_v5.5


ENTRYPOINT [ "/opt/esp/entrypoint.sh" ]
CMD [ "/bin/bash" ]
